dubbo:
  application:
    name: dubbo-consumer
    qos-port: 33333
  registry:
    address: zookeeper://43.139.72.36:2181
    timeout: 100000
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: org.amir.service
server:
  port: 8081